### ISSUE TITLE
No serialization support?

### ISSUE THREAD

**Issue by Larivact** [hjson/hjson-cs#1]
`System.Web.Script.Serialization.JavaScriptSerializer` allows you to do sth like:

``` c#
class Person
{
    public Person(string name, int age)
    {
        this.name = name;
        this.age = age;
    }

    public string name;
    public int age;
}
```

``` c#
List <Person> persons = new List <Person> { new Person("Joe", 30) };
var json = new JavaScriptSerializer().Serialize(persons);
//[{"name":"Joe","age":30}]
```

Am I missing something? I don't see myself using `JavaScriptSerializer` and then Hjson to convert it from JSON to Hjson.

**Comment by laktak** [comment]
What are you trying to do? Hjson should be used for configuration or for debugging, not as data storage like your sample implies.

Eg. for loading from `{ test: "foo" }`:

```
      var data=HjsonValue.Load("test.hjson").Qo();
      Console.WriteLine(data.Qs("hello"));
```

**Comment by Larivact** [comment]
Huh, I missed that Hjson is only intended for configs. Now that I think about it, it doesn't make much sense to use it for data storage. Thanks for clarifying.
