### ISSUE TITLE
using Qs() with a number fails with "not supported for type number"

### ISSUE THREAD

**Issue by gregmac** [hjson/hjson-cs#3]
I'm reading a value that can be any user-entered value, and in this case happens to be a number.

Sample repro HJSON:

```
{
  Value: 1234
}
```

Code

```
var test = HjsonValue.Load("sample.json");
test.Qo().Qs("Value");
```

Full exception:

```
JsonUtil.Qs not supported for type number [key:Value]!
  at Hjson.JsonUtil.Qs(JsonObject json, String key, String defaultValue)
```

In this case, the value is not supposed to be numeric, it just happens to be a number (literally I want to read it as string value `"1234"`). I don't think it makes sense to ask users to put quotes around string values that happen to be comprised of only ASCII digit characters.

**Comment by laktak** [comment]
I've added `Qstr()` for your use case. 

```
test.Qo().Qstr("Value");
```

Let me know if it works for you.

**Comment by gregmac** [comment]
Yes, that does work, though I think it should just be the behaviour of `Qs()` rather than a new method. At best, it should be an optional overload for strict type parsing (and off by default).

In addition to numbers, this also affects the values `true` and `false` (_JsonUtil.Qs not supported for type boolean_). 

Changing the default does in fact break backwards compatibility IF you are relying on the typed parsing functions Qs() for validation AND 'true', 'false', and all-numeric are your only invalid values. In real cases, I imagine if you need validation, you're going to write validation, and thus the Hjson library should do what I tell it to do (in other words: if I tell it to give me a string value but it's really a number, that's my problem if it really is a problem for me).

**Comment by laktak** [comment]
The readme does not mention it but this library includes a JSON reader/writer in addition to Hjson. `Qs()` is an exension method for `JsonValue`/`JsonObject` that is used by both readers/writers.

There are several other methods (`Qb()`, `Qi()`, `Qd()`, ...) that return the underlying value depending on the type. Changing `Qs()` would produce unexpected results.

`Qstr()` converts everything to string (including bool) and appears to be exactly what you are asking for ...?

**Comment by gregmac** [comment]
> Qs() is an exension method for JsonValue/JsonObject that is used by both readers/writers.

I don't see that -- `Qs()` isn't referenced anywhere else than JsonUtil and the Sample program.cs.

> Changing `Qs()` would produce unexpected results.

I guess I really just disagree with the current behaviour specifically because it means that there are magic string values that can't be read as strings, and I really don't see the use case for why the library should consider the strings `true`, `false` and `1234` as invalid, but `true!`, `not false`, and `v12.34` in the same place as perfectly fine. 

If a developer wants to read a boolean or numeric value they'll use the `Qb()` or `Qi()` or `Qd()`; if they've called `Qs()` then they want a string. If the developer wants to consider `"true"`, `"false"`, `"1234"`, `"pickle"` or anything else as invalid string values, that should be in their application logic.

I can see the argument for non-primitive types: if the value contains an array or object, Qs() can throw. This restricts the special cases to values beginning with `[` or `{`: if you want a string that starts with one of those, you must put quotes around it. This is actually true for the hjson format, regardless of these extension methods.

I'll submit a PR with my opinion on this.

**Comment by laktak** [comment]
I get your point and I agree that there is a use case - which is why I added `Qstr()`. Just use it instead of `Qs()`. 

If you think `Qstr()` is not optimal (because of arrays/objects/null/...) feel free to submit a PR to change it. Just don't break the API by changing `Qs()`.

**Comment by gregmac** [comment]
Clearly I did not get my point across. I think it's a (hidden) bug that the the values `true`, `false` and `1234` break `Qs()` -- and it's the worst kind of bug because it's only discovered when reading data provided by a 3rd party source that happens to contain magic strings. IMHO it's very not obvious behaviour to a developer using this library.

Anyway, clearly you disagree with me and like this behaviour, so I guess the `Qstr()` method solves it. Maybe you can at least put in a warning about the behaviour similar to what I did in #5.

**Comment by laktak** [comment]
I've updated `Qstr()` and the docs/readme. I really appreciate your input and while we may disagree, I hope this is an acceptable solution.
