### ISSUE TITLE
Add unit tests for .NET code

### ISSUE THREAD

**Issue by gregmac** [hjson/hjson-cs#4]
Existing code has some tests only for the parser, and there's no test for any of the actual API (for example, I would have made a test to illustrate #3 but there's no test framework). 

Now that #2 has been merged, are you open to adding some unit tests? Obviously Travis will have to run them, but any preference on test framework (NUnit vs others)?

**Comment by laktak** [comment]
That's great! 👍  I haven't used NUnit so I'll leave that up to you (as long as it works with travis/mono and is "easy" to set up).

**Comment by laktak** [comment]
Closing for now.
